set -g prefix C-b
bind-key C-b send-prefix

# Enable mouse support (scroll, click, resize panes)
set -g mouse on

# Enable 256 colors
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g status-position bottom
set -g status-bg colour234
set -g status-fg colour137
set -g status-left ''
set -g status-right '#[fg=colour233,bg=colour241,bold] %d/%m #[fg=colour233,bg=colour245,bold] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20
setw -g mode-keys vi

setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

set-option -g history-limit 5000

set -s set-clipboard on
set -sg escape-time 10

bind g display-popup -E -w 90% -h 90% -d "#{pane_current_path}" lazygit
bind j display-popup -E -w 80% -h 70% "tmux attach -t scratch || tmux new -s scratch"
bind T run-shell "sesh connect \"$(sesh list --icons | fzf-tmux -p 60%,70% --no-border)\""

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'

run '~/.tmux/plugins/tpm/tpm'
