require("viktor.core.options")
require("viktor.core.keymaps")
require("viktor.core.godot").setup()
require("viktor.tools").setup()
require("viktor.core.diagnostics")
require("viktor.core.overrides")
require("viktor.core.ts_motions").setup()
